package com.qhit.lh.gr3.wjw.connect.bean;
// Generated 2018-3-8 11:27:08 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * PaperClass generated by hbm2java
 */
public class PaperClass implements java.io.Serializable {

	private Integer pcId;
	private int pid;
	private String ccode;
	private Date examDate;
	private Date endDate;

	public PaperClass() {
	}

	public PaperClass(int pid, String ccode, Date examDate, Date endDate) {
		this.pid = pid;
		this.ccode = ccode;
		this.examDate = examDate;
		this.endDate = endDate;
	}

	public Integer getPcId() {
		return this.pcId;
	}

	public void setPcId(Integer pcId) {
		this.pcId = pcId;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public String getCcode() {
		return this.ccode;
	}

	public void setCcode(String ccode) {
		this.ccode = ccode;
	}

	public Date getExamDate() {
		return this.examDate;
	}

	public void setExamDate(Date examDate) {
		this.examDate = examDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
