package com.qhit.lh.gr3.wjw.connect.bean;
// Generated 2018-3-8 11:27:08 by Hibernate Tools 5.2.8.Final

/**
 * PaperWquestion generated by hbm2java
 */
public class PaperWquestion implements java.io.Serializable {

	private Integer id;
	private int pid;
	private int qid;

	public PaperWquestion() {
	}

	public PaperWquestion(int pid, int qid) {
		this.pid = pid;
		this.qid = qid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

}
