package com.qhit.lh.gr3.wjw.user.bean;
// Generated 2017-12-12 23:25:16 by Hibernate Tools 5.2.6.Final


/**
 * TUser generated by hbm2java
 */
public class TUser {

	private Integer id;
	private String name;
	private String password;
	private String address;

	private TInfo tinfo;
	public TUser() {
	}

	public TUser(String name, String password, String address) {
		this.name = name;
		this.password = password;
		this.address = address;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public TInfo getTinfo() {
		return tinfo;
	}

	public void setTinfo(TInfo tinfo) {
		this.tinfo = tinfo;
	}

}
