package com.qhit.lh.gr3.wjw.classinfo.bean;
// Generated 2018-3-8 11:27:08 by Hibernate Tools 5.2.8.Final

import java.io.Serializable;
import java.util.Date;

/**
 * TClassInfo generated by hbm2java
 */
public class TClassInfo implements java.io.Serializable {

	private String ccode;
	private String cname;
	private String major;
	private Serializable insId;
	private Serializable iecId;
	private Date cdate;
	private Integer g1num;
	private Integer g2num;
	private Integer g3num;
	private Integer ccodeId;
	private String cremark;

	public TClassInfo() {
	}

	public TClassInfo(String ccode, String cname, String major, Date cdate) {
		this.ccode = ccode;
		this.cname = cname;
		this.major = major;
		this.cdate = cdate;
	}

	public TClassInfo(String ccode, String cname, String major, Serializable insId, Serializable iecId, Date cdate,
			Integer g1num, Integer g2num, Integer g3num, Integer ccodeId, String cremark) {
		this.ccode = ccode;
		this.cname = cname;
		this.major = major;
		this.insId = insId;
		this.iecId = iecId;
		this.cdate = cdate;
		this.g1num = g1num;
		this.g2num = g2num;
		this.g3num = g3num;
		this.ccodeId = ccodeId;
		this.cremark = cremark;
	}

	public String getCcode() {
		return this.ccode;
	}

	public void setCcode(String ccode) {
		this.ccode = ccode;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public Serializable getInsId() {
		return this.insId;
	}

	public void setInsId(Serializable insId) {
		this.insId = insId;
	}

	public Serializable getIecId() {
		return this.iecId;
	}

	public void setIecId(Serializable iecId) {
		this.iecId = iecId;
	}

	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public Integer getG1num() {
		return this.g1num;
	}

	public void setG1num(Integer g1num) {
		this.g1num = g1num;
	}

	public Integer getG2num() {
		return this.g2num;
	}

	public void setG2num(Integer g2num) {
		this.g2num = g2num;
	}

	public Integer getG3num() {
		return this.g3num;
	}

	public void setG3num(Integer g3num) {
		this.g3num = g3num;
	}

	public Integer getCcodeId() {
		return this.ccodeId;
	}

	public void setCcodeId(Integer ccodeId) {
		this.ccodeId = ccodeId;
	}

	public String getCremark() {
		return this.cremark;
	}

	public void setCremark(String cremark) {
		this.cremark = cremark;
	}

}
