package com.qhit.lh.wjw.examScores.bean;
// Generated 2018-3-8 12:10:56 by Hibernate Tools 5.2.9.Final

/**
 * TExamscores generated by hbm2java
 */
public class TExamscores implements java.io.Serializable {

	private Integer eid;
	private int sid;
	private int scores;

	public TExamscores() {
	}

	public TExamscores(int sid, int scores) {
		this.sid = sid;
		this.scores = scores;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public int getScores() {
		return this.scores;
	}

	public void setScores(int scores) {
		this.scores = scores;
	}

}
