package com.qhit.lh.gr3.wjw.paper.bean;
// Generated 2018-3-8 11:27:08 by Hibernate Tools 5.2.8.Final

/**
 * TPaper generated by hbm2java
 */
public class TPaper implements java.io.Serializable {

	private Integer pid;
	private String pname;
	private int ptime;
	private int ptotalScore;
	private int csId;
	private int qtotal;
	private Double qscore;
	private String ptype;
	private String pstate;

	public TPaper() {
	}

	public TPaper(String pname, int ptime, int ptotalScore, int csId, int qtotal, String ptype, String pstate) {
		this.pname = pname;
		this.ptime = ptime;
		this.ptotalScore = ptotalScore;
		this.csId = csId;
		this.qtotal = qtotal;
		this.ptype = ptype;
		this.pstate = pstate;
	}

	public TPaper(String pname, int ptime, int ptotalScore, int csId, int qtotal, Double qscore, String ptype,
			String pstate) {
		this.pname = pname;
		this.ptime = ptime;
		this.ptotalScore = ptotalScore;
		this.csId = csId;
		this.qtotal = qtotal;
		this.qscore = qscore;
		this.ptype = ptype;
		this.pstate = pstate;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public int getPtime() {
		return this.ptime;
	}

	public void setPtime(int ptime) {
		this.ptime = ptime;
	}

	public int getPtotalScore() {
		return this.ptotalScore;
	}

	public void setPtotalScore(int ptotalScore) {
		this.ptotalScore = ptotalScore;
	}

	public int getCsId() {
		return this.csId;
	}

	public void setCsId(int csId) {
		this.csId = csId;
	}

	public int getQtotal() {
		return this.qtotal;
	}

	public void setQtotal(int qtotal) {
		this.qtotal = qtotal;
	}

	public Double getQscore() {
		return this.qscore;
	}

	public void setQscore(Double qscore) {
		this.qscore = qscore;
	}

	public String getPtype() {
		return this.ptype;
	}

	public void setPtype(String ptype) {
		this.ptype = ptype;
	}

	public String getPstate() {
		return this.pstate;
	}

	public void setPstate(String pstate) {
		this.pstate = pstate;
	}

}
